NET USE H: /DELETE
NET USE H: \\dpextfp1\USERS$\btsheridan$

NET USE M: /DELETE
NET USE M: \\dpextfp1\APPLICATIONS

NET USE P: /DELETE
NET USE P: \\dpiifp2\COMMON$

NET USE Q: /DELETE
NET USE Q: \\dpextfp1\DEPARTMENTS$\BIN\DOCUMENT

NET USE S: /DELETE
NET USE S: \\dpextfp1\DEPARTMENTS$

NET USE T: /DELETE
NET USE T: \\dpextfp1\ENGSCAN

NET USE V: /DELETE
NET USE V: \\dpextfp1\CADSHARE	
